version: '3'

services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      # change the port from 5000 to 5002 to avoid conflict with MacOS Control Center
      - "5002:5000"

  customers_api:
    build: customers_api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./customers_api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5001:5000"

  client:
    tty: true
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules:
